//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("MVCProjectModel", "FK__MIS_Field__Field__276EDEB3", "MIS_GroupFieldsMaster", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MVCProject.Api.Models.MIS_GroupFieldsMaster), "MIS_FieldData", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MVCProject.Api.Models.MIS_FieldData), true)]
[assembly: EdmRelationshipAttribute("MVCProjectModel", "FK__MIS_Field__Repor__267ABA7A", "MIS_MISReport", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MVCProject.Api.Models.MIS_MISReport), "MIS_FieldData", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MVCProject.Api.Models.MIS_FieldData), true)]
[assembly: EdmRelationshipAttribute("MVCProjectModel", "FK__MIS_Group__Group__1920BF5C", "MIS_GroupsMaster", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MVCProject.Api.Models.MIS_GroupsMaster), "MIS_GroupFieldsMaster", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MVCProject.Api.Models.MIS_GroupFieldsMaster), true)]
[assembly: EdmRelationshipAttribute("MVCProjectModel", "FK__MIS_MISRe__Proje__22AA2996", "MIS_ProjectMaster", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MVCProject.Api.Models.MIS_ProjectMaster), "MIS_MISReport", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MVCProject.Api.Models.MIS_MISReport), true)]
[assembly: EdmRelationshipAttribute("MVCProjectModel", "FK__MIS_MISRe__Statu__239E4DCF", "MIS_StatusMaster", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MVCProject.Api.Models.MIS_StatusMaster), "MIS_MISReport", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MVCProject.Api.Models.MIS_MISReport), true)]
[assembly: EdmRelationshipAttribute("MVCProjectModel", "FK__MIS_MISRe__Verti__21B6055D", "MIS_VerticalMaster", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MVCProject.Api.Models.MIS_VerticalMaster), "MIS_MISReport", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MVCProject.Api.Models.MIS_MISReport), true)]
[assembly: EdmRelationshipAttribute("MVCProjectModel", "FK__MIS_Users__RoleI__145C0A3F", "MIS_RoleMaster", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MVCProject.Api.Models.MIS_RoleMaster), "MIS_Users", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MVCProject.Api.Models.MIS_Users), true)]

#endregion

namespace MVCProject.Api.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MVCProjectEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MVCProjectEntities object using the connection string found in the 'MVCProjectEntities' section of the application configuration file.
        /// </summary>
        public MVCProjectEntities() : base("name=MVCProjectEntities", "MVCProjectEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MVCProjectEntities object.
        /// </summary>
        public MVCProjectEntities(string connectionString) : base(connectionString, "MVCProjectEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MVCProjectEntities object.
        /// </summary>
        public MVCProjectEntities(EntityConnection connection) : base(connection, "MVCProjectEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MIS_FieldData> MIS_FieldData
        {
            get
            {
                if ((_MIS_FieldData == null))
                {
                    _MIS_FieldData = base.CreateObjectSet<MIS_FieldData>("MIS_FieldData");
                }
                return _MIS_FieldData;
            }
        }
        private ObjectSet<MIS_FieldData> _MIS_FieldData;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MIS_GroupFieldsMaster> MIS_GroupFieldsMaster
        {
            get
            {
                if ((_MIS_GroupFieldsMaster == null))
                {
                    _MIS_GroupFieldsMaster = base.CreateObjectSet<MIS_GroupFieldsMaster>("MIS_GroupFieldsMaster");
                }
                return _MIS_GroupFieldsMaster;
            }
        }
        private ObjectSet<MIS_GroupFieldsMaster> _MIS_GroupFieldsMaster;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MIS_GroupsMaster> MIS_GroupsMaster
        {
            get
            {
                if ((_MIS_GroupsMaster == null))
                {
                    _MIS_GroupsMaster = base.CreateObjectSet<MIS_GroupsMaster>("MIS_GroupsMaster");
                }
                return _MIS_GroupsMaster;
            }
        }
        private ObjectSet<MIS_GroupsMaster> _MIS_GroupsMaster;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MIS_MISReport> MIS_MISReport
        {
            get
            {
                if ((_MIS_MISReport == null))
                {
                    _MIS_MISReport = base.CreateObjectSet<MIS_MISReport>("MIS_MISReport");
                }
                return _MIS_MISReport;
            }
        }
        private ObjectSet<MIS_MISReport> _MIS_MISReport;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MIS_ProjectMaster> MIS_ProjectMaster
        {
            get
            {
                if ((_MIS_ProjectMaster == null))
                {
                    _MIS_ProjectMaster = base.CreateObjectSet<MIS_ProjectMaster>("MIS_ProjectMaster");
                }
                return _MIS_ProjectMaster;
            }
        }
        private ObjectSet<MIS_ProjectMaster> _MIS_ProjectMaster;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MIS_RoleMaster> MIS_RoleMaster
        {
            get
            {
                if ((_MIS_RoleMaster == null))
                {
                    _MIS_RoleMaster = base.CreateObjectSet<MIS_RoleMaster>("MIS_RoleMaster");
                }
                return _MIS_RoleMaster;
            }
        }
        private ObjectSet<MIS_RoleMaster> _MIS_RoleMaster;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MIS_StatusMaster> MIS_StatusMaster
        {
            get
            {
                if ((_MIS_StatusMaster == null))
                {
                    _MIS_StatusMaster = base.CreateObjectSet<MIS_StatusMaster>("MIS_StatusMaster");
                }
                return _MIS_StatusMaster;
            }
        }
        private ObjectSet<MIS_StatusMaster> _MIS_StatusMaster;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MIS_Users> MIS_Users
        {
            get
            {
                if ((_MIS_Users == null))
                {
                    _MIS_Users = base.CreateObjectSet<MIS_Users>("MIS_Users");
                }
                return _MIS_Users;
            }
        }
        private ObjectSet<MIS_Users> _MIS_Users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MIS_VerticalMaster> MIS_VerticalMaster
        {
            get
            {
                if ((_MIS_VerticalMaster == null))
                {
                    _MIS_VerticalMaster = base.CreateObjectSet<MIS_VerticalMaster>("MIS_VerticalMaster");
                }
                return _MIS_VerticalMaster;
            }
        }
        private ObjectSet<MIS_VerticalMaster> _MIS_VerticalMaster;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Designation> Designations
        {
            get
            {
                if ((_Designations == null))
                {
                    _Designations = base.CreateObjectSet<Designation>("Designations");
                }
                return _Designations;
            }
        }
        private ObjectSet<Designation> _Designations;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MIS_FieldData EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMIS_FieldData(MIS_FieldData mIS_FieldData)
        {
            base.AddObject("MIS_FieldData", mIS_FieldData);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MIS_GroupFieldsMaster EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMIS_GroupFieldsMaster(MIS_GroupFieldsMaster mIS_GroupFieldsMaster)
        {
            base.AddObject("MIS_GroupFieldsMaster", mIS_GroupFieldsMaster);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MIS_GroupsMaster EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMIS_GroupsMaster(MIS_GroupsMaster mIS_GroupsMaster)
        {
            base.AddObject("MIS_GroupsMaster", mIS_GroupsMaster);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MIS_MISReport EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMIS_MISReport(MIS_MISReport mIS_MISReport)
        {
            base.AddObject("MIS_MISReport", mIS_MISReport);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MIS_ProjectMaster EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMIS_ProjectMaster(MIS_ProjectMaster mIS_ProjectMaster)
        {
            base.AddObject("MIS_ProjectMaster", mIS_ProjectMaster);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MIS_RoleMaster EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMIS_RoleMaster(MIS_RoleMaster mIS_RoleMaster)
        {
            base.AddObject("MIS_RoleMaster", mIS_RoleMaster);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MIS_StatusMaster EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMIS_StatusMaster(MIS_StatusMaster mIS_StatusMaster)
        {
            base.AddObject("MIS_StatusMaster", mIS_StatusMaster);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MIS_Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMIS_Users(MIS_Users mIS_Users)
        {
            base.AddObject("MIS_Users", mIS_Users);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MIS_VerticalMaster EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMIS_VerticalMaster(MIS_VerticalMaster mIS_VerticalMaster)
        {
            base.AddObject("MIS_VerticalMaster", mIS_VerticalMaster);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Designations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDesignations(Designation designation)
        {
            base.AddObject("Designations", designation);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="email">No Metadata Documentation available.</param>
        /// <param name="password">No Metadata Documentation available.</param>
        public ObjectResult<USP_MIS_AuthenticateUser_Result> USP_MIS_AuthenticateUser(global::System.String email, global::System.String password)
        {
            ObjectParameter emailParameter;
            if (email != null)
            {
                emailParameter = new ObjectParameter("Email", email);
            }
            else
            {
                emailParameter = new ObjectParameter("Email", typeof(global::System.String));
            }
    
            ObjectParameter passwordParameter;
            if (password != null)
            {
                passwordParameter = new ObjectParameter("Password", password);
            }
            else
            {
                passwordParameter = new ObjectParameter("Password", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<USP_MIS_AuthenticateUser_Result>("USP_MIS_AuthenticateUser", emailParameter, passwordParameter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MVCProjectModel", Name="Designation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Designation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Designation object.
        /// </summary>
        /// <param name="designationId">Initial value of the DesignationId property.</param>
        public static Designation CreateDesignation(global::System.Int32 designationId)
        {
            Designation designation = new Designation();
            designation.DesignationId = designationId;
            return designation;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DesignationId
        {
            get
            {
                return _DesignationId;
            }
            set
            {
                if (_DesignationId != value)
                {
                    OnDesignationIdChanging(value);
                    ReportPropertyChanging("DesignationId");
                    _DesignationId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DesignationId");
                    OnDesignationIdChanged();
                }
            }
        }
        private global::System.Int32 _DesignationId;
        partial void OnDesignationIdChanging(global::System.Int32 value);
        partial void OnDesignationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DesignationName
        {
            get
            {
                return _DesignationName;
            }
            set
            {
                OnDesignationNameChanging(value);
                ReportPropertyChanging("DesignationName");
                _DesignationName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DesignationName");
                OnDesignationNameChanged();
            }
        }
        private global::System.String _DesignationName;
        partial void OnDesignationNameChanging(global::System.String value);
        partial void OnDesignationNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsActive;
        partial void OnIsActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnIsActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Remarks
        {
            get
            {
                return _Remarks;
            }
            set
            {
                OnRemarksChanging(value);
                ReportPropertyChanging("Remarks");
                _Remarks = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Remarks");
                OnRemarksChanged();
            }
        }
        private global::System.String _Remarks;
        partial void OnRemarksChanging(global::System.String value);
        partial void OnRemarksChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MVCProjectModel", Name="MIS_FieldData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MIS_FieldData : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MIS_FieldData object.
        /// </summary>
        /// <param name="dataId">Initial value of the DataId property.</param>
        public static MIS_FieldData CreateMIS_FieldData(global::System.Int32 dataId)
        {
            MIS_FieldData mIS_FieldData = new MIS_FieldData();
            mIS_FieldData.DataId = dataId;
            return mIS_FieldData;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DataId
        {
            get
            {
                return _DataId;
            }
            set
            {
                if (_DataId != value)
                {
                    OnDataIdChanging(value);
                    ReportPropertyChanging("DataId");
                    _DataId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DataId");
                    OnDataIdChanged();
                }
            }
        }
        private global::System.Int32 _DataId;
        partial void OnDataIdChanging(global::System.Int32 value);
        partial void OnDataIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ReportId
        {
            get
            {
                return _ReportId;
            }
            set
            {
                OnReportIdChanging(value);
                ReportPropertyChanging("ReportId");
                _ReportId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReportId");
                OnReportIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ReportId;
        partial void OnReportIdChanging(Nullable<global::System.Int32> value);
        partial void OnReportIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FieldId
        {
            get
            {
                return _FieldId;
            }
            set
            {
                OnFieldIdChanging(value);
                ReportPropertyChanging("FieldId");
                _FieldId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FieldId");
                OnFieldIdChanged();
            }
        }
        private Nullable<global::System.Int32> _FieldId;
        partial void OnFieldIdChanging(Nullable<global::System.Int32> value);
        partial void OnFieldIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FieldValue
        {
            get
            {
                return _FieldValue;
            }
            set
            {
                OnFieldValueChanging(value);
                ReportPropertyChanging("FieldValue");
                _FieldValue = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FieldValue");
                OnFieldValueChanged();
            }
        }
        private global::System.String _FieldValue;
        partial void OnFieldValueChanging(global::System.String value);
        partial void OnFieldValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Remarks
        {
            get
            {
                return _Remarks;
            }
            set
            {
                OnRemarksChanging(value);
                ReportPropertyChanging("Remarks");
                _Remarks = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Remarks");
                OnRemarksChanged();
            }
        }
        private global::System.String _Remarks;
        partial void OnRemarksChanging(global::System.String value);
        partial void OnRemarksChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EntryBy
        {
            get
            {
                return _EntryBy;
            }
            set
            {
                OnEntryByChanging(value);
                ReportPropertyChanging("EntryBy");
                _EntryBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EntryBy");
                OnEntryByChanged();
            }
        }
        private Nullable<global::System.Int32> _EntryBy;
        partial void OnEntryByChanging(Nullable<global::System.Int32> value);
        partial void OnEntryByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EntryDate
        {
            get
            {
                return _EntryDate;
            }
            set
            {
                OnEntryDateChanging(value);
                ReportPropertyChanging("EntryDate");
                _EntryDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EntryDate");
                OnEntryDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _EntryDate;
        partial void OnEntryDateChanging(Nullable<global::System.DateTime> value);
        partial void OnEntryDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UpdateBy
        {
            get
            {
                return _UpdateBy;
            }
            set
            {
                OnUpdateByChanging(value);
                ReportPropertyChanging("UpdateBy");
                _UpdateBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdateBy");
                OnUpdateByChanged();
            }
        }
        private Nullable<global::System.Int32> _UpdateBy;
        partial void OnUpdateByChanging(Nullable<global::System.Int32> value);
        partial void OnUpdateByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UpdateDate
        {
            get
            {
                return _UpdateDate;
            }
            set
            {
                OnUpdateDateChanging(value);
                ReportPropertyChanging("UpdateDate");
                _UpdateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdateDate");
                OnUpdateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _UpdateDate;
        partial void OnUpdateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnUpdateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsActive;
        partial void OnIsActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnIsActiveChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCProjectModel", "FK__MIS_Field__Field__276EDEB3", "MIS_GroupFieldsMaster")]
        public MIS_GroupFieldsMaster MIS_GroupFieldsMaster
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MIS_GroupFieldsMaster>("MVCProjectModel.FK__MIS_Field__Field__276EDEB3", "MIS_GroupFieldsMaster").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MIS_GroupFieldsMaster>("MVCProjectModel.FK__MIS_Field__Field__276EDEB3", "MIS_GroupFieldsMaster").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MIS_GroupFieldsMaster> MIS_GroupFieldsMasterReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MIS_GroupFieldsMaster>("MVCProjectModel.FK__MIS_Field__Field__276EDEB3", "MIS_GroupFieldsMaster");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MIS_GroupFieldsMaster>("MVCProjectModel.FK__MIS_Field__Field__276EDEB3", "MIS_GroupFieldsMaster", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCProjectModel", "FK__MIS_Field__Repor__267ABA7A", "MIS_MISReport")]
        public MIS_MISReport MIS_MISReport
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MIS_MISReport>("MVCProjectModel.FK__MIS_Field__Repor__267ABA7A", "MIS_MISReport").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MIS_MISReport>("MVCProjectModel.FK__MIS_Field__Repor__267ABA7A", "MIS_MISReport").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MIS_MISReport> MIS_MISReportReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MIS_MISReport>("MVCProjectModel.FK__MIS_Field__Repor__267ABA7A", "MIS_MISReport");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MIS_MISReport>("MVCProjectModel.FK__MIS_Field__Repor__267ABA7A", "MIS_MISReport", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MVCProjectModel", Name="MIS_GroupFieldsMaster")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MIS_GroupFieldsMaster : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MIS_GroupFieldsMaster object.
        /// </summary>
        /// <param name="fieldId">Initial value of the FieldId property.</param>
        public static MIS_GroupFieldsMaster CreateMIS_GroupFieldsMaster(global::System.Int32 fieldId)
        {
            MIS_GroupFieldsMaster mIS_GroupFieldsMaster = new MIS_GroupFieldsMaster();
            mIS_GroupFieldsMaster.FieldId = fieldId;
            return mIS_GroupFieldsMaster;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FieldId
        {
            get
            {
                return _FieldId;
            }
            set
            {
                if (_FieldId != value)
                {
                    OnFieldIdChanging(value);
                    ReportPropertyChanging("FieldId");
                    _FieldId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FieldId");
                    OnFieldIdChanged();
                }
            }
        }
        private global::System.Int32 _FieldId;
        partial void OnFieldIdChanging(global::System.Int32 value);
        partial void OnFieldIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FieldName
        {
            get
            {
                return _FieldName;
            }
            set
            {
                OnFieldNameChanging(value);
                ReportPropertyChanging("FieldName");
                _FieldName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FieldName");
                OnFieldNameChanged();
            }
        }
        private global::System.String _FieldName;
        partial void OnFieldNameChanging(global::System.String value);
        partial void OnFieldNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GroupId
        {
            get
            {
                return _GroupId;
            }
            set
            {
                OnGroupIdChanging(value);
                ReportPropertyChanging("GroupId");
                _GroupId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GroupId");
                OnGroupIdChanged();
            }
        }
        private Nullable<global::System.Int32> _GroupId;
        partial void OnGroupIdChanging(Nullable<global::System.Int32> value);
        partial void OnGroupIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsActive;
        partial void OnIsActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnIsActiveChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCProjectModel", "FK__MIS_Field__Field__276EDEB3", "MIS_FieldData")]
        public EntityCollection<MIS_FieldData> MIS_FieldData
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MIS_FieldData>("MVCProjectModel.FK__MIS_Field__Field__276EDEB3", "MIS_FieldData");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MIS_FieldData>("MVCProjectModel.FK__MIS_Field__Field__276EDEB3", "MIS_FieldData", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCProjectModel", "FK__MIS_Group__Group__1920BF5C", "MIS_GroupsMaster")]
        public MIS_GroupsMaster MIS_GroupsMaster
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MIS_GroupsMaster>("MVCProjectModel.FK__MIS_Group__Group__1920BF5C", "MIS_GroupsMaster").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MIS_GroupsMaster>("MVCProjectModel.FK__MIS_Group__Group__1920BF5C", "MIS_GroupsMaster").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MIS_GroupsMaster> MIS_GroupsMasterReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MIS_GroupsMaster>("MVCProjectModel.FK__MIS_Group__Group__1920BF5C", "MIS_GroupsMaster");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MIS_GroupsMaster>("MVCProjectModel.FK__MIS_Group__Group__1920BF5C", "MIS_GroupsMaster", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MVCProjectModel", Name="MIS_GroupsMaster")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MIS_GroupsMaster : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MIS_GroupsMaster object.
        /// </summary>
        /// <param name="groupId">Initial value of the GroupId property.</param>
        public static MIS_GroupsMaster CreateMIS_GroupsMaster(global::System.Int32 groupId)
        {
            MIS_GroupsMaster mIS_GroupsMaster = new MIS_GroupsMaster();
            mIS_GroupsMaster.GroupId = groupId;
            return mIS_GroupsMaster;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GroupId
        {
            get
            {
                return _GroupId;
            }
            set
            {
                if (_GroupId != value)
                {
                    OnGroupIdChanging(value);
                    ReportPropertyChanging("GroupId");
                    _GroupId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GroupId");
                    OnGroupIdChanged();
                }
            }
        }
        private global::System.Int32 _GroupId;
        partial void OnGroupIdChanging(global::System.Int32 value);
        partial void OnGroupIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GroupName
        {
            get
            {
                return _GroupName;
            }
            set
            {
                OnGroupNameChanging(value);
                ReportPropertyChanging("GroupName");
                _GroupName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GroupName");
                OnGroupNameChanged();
            }
        }
        private global::System.String _GroupName;
        partial void OnGroupNameChanging(global::System.String value);
        partial void OnGroupNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsActive;
        partial void OnIsActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnIsActiveChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCProjectModel", "FK__MIS_Group__Group__1920BF5C", "MIS_GroupFieldsMaster")]
        public EntityCollection<MIS_GroupFieldsMaster> MIS_GroupFieldsMaster
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MIS_GroupFieldsMaster>("MVCProjectModel.FK__MIS_Group__Group__1920BF5C", "MIS_GroupFieldsMaster");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MIS_GroupFieldsMaster>("MVCProjectModel.FK__MIS_Group__Group__1920BF5C", "MIS_GroupFieldsMaster", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MVCProjectModel", Name="MIS_MISReport")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MIS_MISReport : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MIS_MISReport object.
        /// </summary>
        /// <param name="reportId">Initial value of the ReportId property.</param>
        public static MIS_MISReport CreateMIS_MISReport(global::System.Int32 reportId)
        {
            MIS_MISReport mIS_MISReport = new MIS_MISReport();
            mIS_MISReport.ReportId = reportId;
            return mIS_MISReport;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ReportId
        {
            get
            {
                return _ReportId;
            }
            set
            {
                if (_ReportId != value)
                {
                    OnReportIdChanging(value);
                    ReportPropertyChanging("ReportId");
                    _ReportId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ReportId");
                    OnReportIdChanged();
                }
            }
        }
        private global::System.Int32 _ReportId;
        partial void OnReportIdChanging(global::System.Int32 value);
        partial void OnReportIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ReportDate
        {
            get
            {
                return _ReportDate;
            }
            set
            {
                OnReportDateChanging(value);
                ReportPropertyChanging("ReportDate");
                _ReportDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReportDate");
                OnReportDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ReportDate;
        partial void OnReportDateChanging(Nullable<global::System.DateTime> value);
        partial void OnReportDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> VerticalId
        {
            get
            {
                return _VerticalId;
            }
            set
            {
                OnVerticalIdChanging(value);
                ReportPropertyChanging("VerticalId");
                _VerticalId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VerticalId");
                OnVerticalIdChanged();
            }
        }
        private Nullable<global::System.Int32> _VerticalId;
        partial void OnVerticalIdChanging(Nullable<global::System.Int32> value);
        partial void OnVerticalIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ProjectId
        {
            get
            {
                return _ProjectId;
            }
            set
            {
                OnProjectIdChanging(value);
                ReportPropertyChanging("ProjectId");
                _ProjectId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProjectId");
                OnProjectIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ProjectId;
        partial void OnProjectIdChanging(Nullable<global::System.Int32> value);
        partial void OnProjectIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> StatusId
        {
            get
            {
                return _StatusId;
            }
            set
            {
                OnStatusIdChanging(value);
                ReportPropertyChanging("StatusId");
                _StatusId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StatusId");
                OnStatusIdChanged();
            }
        }
        private Nullable<global::System.Int32> _StatusId;
        partial void OnStatusIdChanging(Nullable<global::System.Int32> value);
        partial void OnStatusIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EntryBy
        {
            get
            {
                return _EntryBy;
            }
            set
            {
                OnEntryByChanging(value);
                ReportPropertyChanging("EntryBy");
                _EntryBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EntryBy");
                OnEntryByChanged();
            }
        }
        private Nullable<global::System.Int32> _EntryBy;
        partial void OnEntryByChanging(Nullable<global::System.Int32> value);
        partial void OnEntryByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EntryDate
        {
            get
            {
                return _EntryDate;
            }
            set
            {
                OnEntryDateChanging(value);
                ReportPropertyChanging("EntryDate");
                _EntryDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EntryDate");
                OnEntryDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _EntryDate;
        partial void OnEntryDateChanging(Nullable<global::System.DateTime> value);
        partial void OnEntryDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UpdateBy
        {
            get
            {
                return _UpdateBy;
            }
            set
            {
                OnUpdateByChanging(value);
                ReportPropertyChanging("UpdateBy");
                _UpdateBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdateBy");
                OnUpdateByChanged();
            }
        }
        private Nullable<global::System.Int32> _UpdateBy;
        partial void OnUpdateByChanging(Nullable<global::System.Int32> value);
        partial void OnUpdateByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UpdateDate
        {
            get
            {
                return _UpdateDate;
            }
            set
            {
                OnUpdateDateChanging(value);
                ReportPropertyChanging("UpdateDate");
                _UpdateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdateDate");
                OnUpdateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _UpdateDate;
        partial void OnUpdateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnUpdateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsActive;
        partial void OnIsActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnIsActiveChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCProjectModel", "FK__MIS_Field__Repor__267ABA7A", "MIS_FieldData")]
        public EntityCollection<MIS_FieldData> MIS_FieldData
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MIS_FieldData>("MVCProjectModel.FK__MIS_Field__Repor__267ABA7A", "MIS_FieldData");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MIS_FieldData>("MVCProjectModel.FK__MIS_Field__Repor__267ABA7A", "MIS_FieldData", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCProjectModel", "FK__MIS_MISRe__Proje__22AA2996", "MIS_ProjectMaster")]
        public MIS_ProjectMaster MIS_ProjectMaster
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MIS_ProjectMaster>("MVCProjectModel.FK__MIS_MISRe__Proje__22AA2996", "MIS_ProjectMaster").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MIS_ProjectMaster>("MVCProjectModel.FK__MIS_MISRe__Proje__22AA2996", "MIS_ProjectMaster").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MIS_ProjectMaster> MIS_ProjectMasterReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MIS_ProjectMaster>("MVCProjectModel.FK__MIS_MISRe__Proje__22AA2996", "MIS_ProjectMaster");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MIS_ProjectMaster>("MVCProjectModel.FK__MIS_MISRe__Proje__22AA2996", "MIS_ProjectMaster", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCProjectModel", "FK__MIS_MISRe__Statu__239E4DCF", "MIS_StatusMaster")]
        public MIS_StatusMaster MIS_StatusMaster
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MIS_StatusMaster>("MVCProjectModel.FK__MIS_MISRe__Statu__239E4DCF", "MIS_StatusMaster").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MIS_StatusMaster>("MVCProjectModel.FK__MIS_MISRe__Statu__239E4DCF", "MIS_StatusMaster").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MIS_StatusMaster> MIS_StatusMasterReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MIS_StatusMaster>("MVCProjectModel.FK__MIS_MISRe__Statu__239E4DCF", "MIS_StatusMaster");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MIS_StatusMaster>("MVCProjectModel.FK__MIS_MISRe__Statu__239E4DCF", "MIS_StatusMaster", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCProjectModel", "FK__MIS_MISRe__Verti__21B6055D", "MIS_VerticalMaster")]
        public MIS_VerticalMaster MIS_VerticalMaster
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MIS_VerticalMaster>("MVCProjectModel.FK__MIS_MISRe__Verti__21B6055D", "MIS_VerticalMaster").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MIS_VerticalMaster>("MVCProjectModel.FK__MIS_MISRe__Verti__21B6055D", "MIS_VerticalMaster").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MIS_VerticalMaster> MIS_VerticalMasterReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MIS_VerticalMaster>("MVCProjectModel.FK__MIS_MISRe__Verti__21B6055D", "MIS_VerticalMaster");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MIS_VerticalMaster>("MVCProjectModel.FK__MIS_MISRe__Verti__21B6055D", "MIS_VerticalMaster", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MVCProjectModel", Name="MIS_ProjectMaster")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MIS_ProjectMaster : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MIS_ProjectMaster object.
        /// </summary>
        /// <param name="projectId">Initial value of the ProjectId property.</param>
        public static MIS_ProjectMaster CreateMIS_ProjectMaster(global::System.Int32 projectId)
        {
            MIS_ProjectMaster mIS_ProjectMaster = new MIS_ProjectMaster();
            mIS_ProjectMaster.ProjectId = projectId;
            return mIS_ProjectMaster;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProjectId
        {
            get
            {
                return _ProjectId;
            }
            set
            {
                if (_ProjectId != value)
                {
                    OnProjectIdChanging(value);
                    ReportPropertyChanging("ProjectId");
                    _ProjectId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProjectId");
                    OnProjectIdChanged();
                }
            }
        }
        private global::System.Int32 _ProjectId;
        partial void OnProjectIdChanging(global::System.Int32 value);
        partial void OnProjectIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProjectName
        {
            get
            {
                return _ProjectName;
            }
            set
            {
                OnProjectNameChanging(value);
                ReportPropertyChanging("ProjectName");
                _ProjectName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProjectName");
                OnProjectNameChanged();
            }
        }
        private global::System.String _ProjectName;
        partial void OnProjectNameChanging(global::System.String value);
        partial void OnProjectNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsActive;
        partial void OnIsActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnIsActiveChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCProjectModel", "FK__MIS_MISRe__Proje__22AA2996", "MIS_MISReport")]
        public EntityCollection<MIS_MISReport> MIS_MISReport
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MIS_MISReport>("MVCProjectModel.FK__MIS_MISRe__Proje__22AA2996", "MIS_MISReport");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MIS_MISReport>("MVCProjectModel.FK__MIS_MISRe__Proje__22AA2996", "MIS_MISReport", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MVCProjectModel", Name="MIS_RoleMaster")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MIS_RoleMaster : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MIS_RoleMaster object.
        /// </summary>
        /// <param name="roleId">Initial value of the RoleId property.</param>
        public static MIS_RoleMaster CreateMIS_RoleMaster(global::System.Int32 roleId)
        {
            MIS_RoleMaster mIS_RoleMaster = new MIS_RoleMaster();
            mIS_RoleMaster.RoleId = roleId;
            return mIS_RoleMaster;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RoleId
        {
            get
            {
                return _RoleId;
            }
            set
            {
                if (_RoleId != value)
                {
                    OnRoleIdChanging(value);
                    ReportPropertyChanging("RoleId");
                    _RoleId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RoleId");
                    OnRoleIdChanged();
                }
            }
        }
        private global::System.Int32 _RoleId;
        partial void OnRoleIdChanging(global::System.Int32 value);
        partial void OnRoleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RoleName
        {
            get
            {
                return _RoleName;
            }
            set
            {
                OnRoleNameChanging(value);
                ReportPropertyChanging("RoleName");
                _RoleName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RoleName");
                OnRoleNameChanged();
            }
        }
        private global::System.String _RoleName;
        partial void OnRoleNameChanging(global::System.String value);
        partial void OnRoleNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsActive;
        partial void OnIsActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnIsActiveChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCProjectModel", "FK__MIS_Users__RoleI__145C0A3F", "MIS_Users")]
        public EntityCollection<MIS_Users> MIS_Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MIS_Users>("MVCProjectModel.FK__MIS_Users__RoleI__145C0A3F", "MIS_Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MIS_Users>("MVCProjectModel.FK__MIS_Users__RoleI__145C0A3F", "MIS_Users", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MVCProjectModel", Name="MIS_StatusMaster")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MIS_StatusMaster : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MIS_StatusMaster object.
        /// </summary>
        /// <param name="statusId">Initial value of the StatusId property.</param>
        public static MIS_StatusMaster CreateMIS_StatusMaster(global::System.Int32 statusId)
        {
            MIS_StatusMaster mIS_StatusMaster = new MIS_StatusMaster();
            mIS_StatusMaster.StatusId = statusId;
            return mIS_StatusMaster;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StatusId
        {
            get
            {
                return _StatusId;
            }
            set
            {
                if (_StatusId != value)
                {
                    OnStatusIdChanging(value);
                    ReportPropertyChanging("StatusId");
                    _StatusId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("StatusId");
                    OnStatusIdChanged();
                }
            }
        }
        private global::System.Int32 _StatusId;
        partial void OnStatusIdChanging(global::System.Int32 value);
        partial void OnStatusIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StatusName
        {
            get
            {
                return _StatusName;
            }
            set
            {
                OnStatusNameChanging(value);
                ReportPropertyChanging("StatusName");
                _StatusName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StatusName");
                OnStatusNameChanged();
            }
        }
        private global::System.String _StatusName;
        partial void OnStatusNameChanging(global::System.String value);
        partial void OnStatusNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsActive;
        partial void OnIsActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnIsActiveChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCProjectModel", "FK__MIS_MISRe__Statu__239E4DCF", "MIS_MISReport")]
        public EntityCollection<MIS_MISReport> MIS_MISReport
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MIS_MISReport>("MVCProjectModel.FK__MIS_MISRe__Statu__239E4DCF", "MIS_MISReport");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MIS_MISReport>("MVCProjectModel.FK__MIS_MISRe__Statu__239E4DCF", "MIS_MISReport", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MVCProjectModel", Name="MIS_Users")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MIS_Users : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MIS_Users object.
        /// </summary>
        /// <param name="userId">Initial value of the UserId property.</param>
        public static MIS_Users CreateMIS_Users(global::System.Int32 userId)
        {
            MIS_Users mIS_Users = new MIS_Users();
            mIS_Users.UserId = userId;
            return mIS_Users;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if (_UserId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _UserId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RoleId
        {
            get
            {
                return _RoleId;
            }
            set
            {
                OnRoleIdChanging(value);
                ReportPropertyChanging("RoleId");
                _RoleId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RoleId");
                OnRoleIdChanged();
            }
        }
        private Nullable<global::System.Int32> _RoleId;
        partial void OnRoleIdChanging(Nullable<global::System.Int32> value);
        partial void OnRoleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EntryBy
        {
            get
            {
                return _EntryBy;
            }
            set
            {
                OnEntryByChanging(value);
                ReportPropertyChanging("EntryBy");
                _EntryBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EntryBy");
                OnEntryByChanged();
            }
        }
        private Nullable<global::System.Int32> _EntryBy;
        partial void OnEntryByChanging(Nullable<global::System.Int32> value);
        partial void OnEntryByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EntryDate
        {
            get
            {
                return _EntryDate;
            }
            set
            {
                OnEntryDateChanging(value);
                ReportPropertyChanging("EntryDate");
                _EntryDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EntryDate");
                OnEntryDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _EntryDate;
        partial void OnEntryDateChanging(Nullable<global::System.DateTime> value);
        partial void OnEntryDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UpdateBy
        {
            get
            {
                return _UpdateBy;
            }
            set
            {
                OnUpdateByChanging(value);
                ReportPropertyChanging("UpdateBy");
                _UpdateBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdateBy");
                OnUpdateByChanged();
            }
        }
        private Nullable<global::System.Int32> _UpdateBy;
        partial void OnUpdateByChanging(Nullable<global::System.Int32> value);
        partial void OnUpdateByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UpdateDate
        {
            get
            {
                return _UpdateDate;
            }
            set
            {
                OnUpdateDateChanging(value);
                ReportPropertyChanging("UpdateDate");
                _UpdateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdateDate");
                OnUpdateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _UpdateDate;
        partial void OnUpdateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnUpdateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsActive;
        partial void OnIsActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnIsActiveChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCProjectModel", "FK__MIS_Users__RoleI__145C0A3F", "MIS_RoleMaster")]
        public MIS_RoleMaster MIS_RoleMaster
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MIS_RoleMaster>("MVCProjectModel.FK__MIS_Users__RoleI__145C0A3F", "MIS_RoleMaster").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MIS_RoleMaster>("MVCProjectModel.FK__MIS_Users__RoleI__145C0A3F", "MIS_RoleMaster").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MIS_RoleMaster> MIS_RoleMasterReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MIS_RoleMaster>("MVCProjectModel.FK__MIS_Users__RoleI__145C0A3F", "MIS_RoleMaster");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MIS_RoleMaster>("MVCProjectModel.FK__MIS_Users__RoleI__145C0A3F", "MIS_RoleMaster", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MVCProjectModel", Name="MIS_VerticalMaster")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MIS_VerticalMaster : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MIS_VerticalMaster object.
        /// </summary>
        /// <param name="verticalId">Initial value of the VerticalId property.</param>
        public static MIS_VerticalMaster CreateMIS_VerticalMaster(global::System.Int32 verticalId)
        {
            MIS_VerticalMaster mIS_VerticalMaster = new MIS_VerticalMaster();
            mIS_VerticalMaster.VerticalId = verticalId;
            return mIS_VerticalMaster;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VerticalId
        {
            get
            {
                return _VerticalId;
            }
            set
            {
                if (_VerticalId != value)
                {
                    OnVerticalIdChanging(value);
                    ReportPropertyChanging("VerticalId");
                    _VerticalId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("VerticalId");
                    OnVerticalIdChanged();
                }
            }
        }
        private global::System.Int32 _VerticalId;
        partial void OnVerticalIdChanging(global::System.Int32 value);
        partial void OnVerticalIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VerticalName
        {
            get
            {
                return _VerticalName;
            }
            set
            {
                OnVerticalNameChanging(value);
                ReportPropertyChanging("VerticalName");
                _VerticalName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VerticalName");
                OnVerticalNameChanged();
            }
        }
        private global::System.String _VerticalName;
        partial void OnVerticalNameChanging(global::System.String value);
        partial void OnVerticalNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsActive;
        partial void OnIsActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnIsActiveChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCProjectModel", "FK__MIS_MISRe__Verti__21B6055D", "MIS_MISReport")]
        public EntityCollection<MIS_MISReport> MIS_MISReport
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MIS_MISReport>("MVCProjectModel.FK__MIS_MISRe__Verti__21B6055D", "MIS_MISReport");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MIS_MISReport>("MVCProjectModel.FK__MIS_MISRe__Verti__21B6055D", "MIS_MISReport", value);
                }
            }
        }

        #endregion

    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="MVCProjectModel", Name="USP_MIS_AuthenticateUser_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class USP_MIS_AuthenticateUser_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new USP_MIS_AuthenticateUser_Result object.
        /// </summary>
        /// <param name="userId">Initial value of the UserId property.</param>
        public static USP_MIS_AuthenticateUser_Result CreateUSP_MIS_AuthenticateUser_Result(global::System.Int32 userId)
        {
            USP_MIS_AuthenticateUser_Result uSP_MIS_AuthenticateUser_Result = new USP_MIS_AuthenticateUser_Result();
            uSP_MIS_AuthenticateUser_Result.UserId = userId;
            return uSP_MIS_AuthenticateUser_Result;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RoleId
        {
            get
            {
                return _RoleId;
            }
            set
            {
                OnRoleIdChanging(value);
                ReportPropertyChanging("RoleId");
                _RoleId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RoleId");
                OnRoleIdChanged();
            }
        }
        private Nullable<global::System.Int32> _RoleId;
        partial void OnRoleIdChanging(Nullable<global::System.Int32> value);
        partial void OnRoleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EntryBy
        {
            get
            {
                return _EntryBy;
            }
            set
            {
                OnEntryByChanging(value);
                ReportPropertyChanging("EntryBy");
                _EntryBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EntryBy");
                OnEntryByChanged();
            }
        }
        private Nullable<global::System.Int32> _EntryBy;
        partial void OnEntryByChanging(Nullable<global::System.Int32> value);
        partial void OnEntryByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EntryDate
        {
            get
            {
                return _EntryDate;
            }
            set
            {
                OnEntryDateChanging(value);
                ReportPropertyChanging("EntryDate");
                _EntryDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EntryDate");
                OnEntryDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _EntryDate;
        partial void OnEntryDateChanging(Nullable<global::System.DateTime> value);
        partial void OnEntryDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UpdateBy
        {
            get
            {
                return _UpdateBy;
            }
            set
            {
                OnUpdateByChanging(value);
                ReportPropertyChanging("UpdateBy");
                _UpdateBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdateBy");
                OnUpdateByChanged();
            }
        }
        private Nullable<global::System.Int32> _UpdateBy;
        partial void OnUpdateByChanging(Nullable<global::System.Int32> value);
        partial void OnUpdateByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UpdateDate
        {
            get
            {
                return _UpdateDate;
            }
            set
            {
                OnUpdateDateChanging(value);
                ReportPropertyChanging("UpdateDate");
                _UpdateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdateDate");
                OnUpdateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _UpdateDate;
        partial void OnUpdateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnUpdateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsActive;
        partial void OnIsActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnIsActiveChanged();

        #endregion

    }

    #endregion

    
}
